export interface LandingPage {
  slug: string;
  title: string;
  description: string;
  h1: string;
  intro: string;
  steps: { step: number; title: string; desc: string }[];
  toolLink: string;
  toolName: string;
  faqs: { q: string; a: string }[];
  keywords: string[];
}

export const landingPages: LandingPage[] = [
  {
    slug: "pdf-to-word-online-free",
    title: "PDF to Word Converter - Free Online, No Sign Up",
    description: "Convert PDF to Word free online. Keep formatting, no registration. 100% browser-based, your files never leave your device.",
    h1: "Convert PDF to Word Online Free",
    intro: "Need to convert your PDF to an editable Word document? You're in the right place. Our PDF to Word converter is 100% free, requires no registration, and works directly in your browser — your files never leave your computer.",
    steps: [
      { step: 1, title: "Upload Your PDF", desc: "Drag and drop your PDF file or click to browse. No file size limits." },
      { step: 2, title: "Convert Automatically", desc: "Our engine instantly converts your PDF to .docx format while preserving formatting." },
      { step: 3, title: "Download & Edit", desc: "Download your Word document and start editing immediately." },
    ],
    toolLink: "/pdf-to-word",
    toolName: "PDF to Word Converter",
    faqs: [
      { q: "Is this PDF to Word converter really free?", a: "Yes! No hidden costs, no registration, unlimited conversions." },
      { q: "Will my formatting be preserved?", a: "Yes, our converter preserves fonts, tables, images and layout as much as possible." },
      { q: "Are my files safe?", a: "100%. All processing happens in your browser. Files never leave your device." },
    ],
    keywords: ["pdf to word", "pdf to docx", "pdf converter", "free pdf to word", "pdf to word online", "convert pdf to word free"],
  },
  {
    slug: "merge-pdf-files-online",
    title: "Merge PDF Files - Free Online PDF Merger",
    description: "Combine multiple PDF files into one document. Free online PDF merger, no sign up, 100% secure browser-based merging.",
    h1: "Merge PDF Files Online Free",
    intro: "Combine multiple PDF documents into a single file in seconds. Our PDF merger lets you reorder pages, rotate them, and merge unlimited PDFs — all for free, directly in your browser.",
    steps: [
      { step: 1, title: "Upload Your PDFs", desc: "Drag multiple PDF files or select them. No limit on file count." },
      { step: 2, title: "Arrange Pages", desc: "Reorder, rotate or delete pages before merging. Full control." },
      { step: 3, title: "Merge & Download", desc: "Click merge and get your combined PDF instantly." },
    ],
    toolLink: "/merge-pdf",
    toolName: "PDF Merger",
    faqs: [
      { q: "How many PDFs can I merge?", a: "Unlimited. Our tool has no file count restrictions." },
      { q: "Can I reorder pages?", a: "Yes! Drag and drop to reorder, rotate or delete individual pages before merging." },
      { q: "Is my data secure?", a: "Absolutely. All merging happens locally in your browser." },
    ],
    keywords: ["merge pdf", "combine pdf", "pdf merger", "merge pdf files", "join pdf", "combine pdf files online"],
  },
  {
    slug: "compress-pdf-under-1mb",
    title: "Compress PDF File Size - Free Online PDF Compressor",
    description: "Reduce PDF file size without losing quality. Compress PDF to under 1MB free online. No sign up, browser-based.",
    h1: "Compress PDF Files Online Free",
    intro: "Got a PDF that's too large to email or upload? Compress it instantly with our free online PDF compressor. Reduce file size by up to 90% while maintaining quality — all in your browser.",
    steps: [
      { step: 1, title: "Upload Your PDF", desc: "Drag your large PDF file. No size limits." },
      { step: 2, title: "Choose Compression", desc: "Select low, recommended or extreme compression level." },
      { step: 3, title: "Download Compressed PDF", desc: "Get your optimized PDF, ready to share or upload." },
    ],
    toolLink: "/compress-pdf",
    toolName: "PDF Compressor",
    faqs: [
      { q: "How much can I compress a PDF?", a: "Typically 30-90% depending on content. Images compress the most." },
      { q: "Will quality be affected?", a: "Recommended mode keeps quality high. Extreme mode reduces quality for max compression." },
      { q: "Is there a file size limit?", a: "No. Works with any size PDF." },
    ],
    keywords: ["compress pdf", "reduce pdf size", "pdf compressor", "compress pdf free", "pdf size reducer", "smaller pdf"],
  },
  {
    slug: "pdf-to-excel-online-free",
    title: "PDF to Excel Converter - Free Online, No Sign Up",
    description: "Convert PDF tables to Excel spreadsheets free online. Extract data from PDF to XLSX instantly. Browser-based, secure.",
    h1: "Convert PDF to Excel Online Free",
    intro: "Need to extract tables from a PDF into an Excel spreadsheet? Our free PDF to Excel converter does exactly that — no registration, no software, just your browser.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Drop your PDF containing tables or data." },
      { step: 2, title: "Convert", desc: "Our engine extracts tables and data into Excel format." },
      { step: 3, title: "Download XLSX", desc: "Get your Excel file ready for analysis." },
    ],
    toolLink: "/pdf-to-excel",
    toolName: "PDF to Excel Converter",
    faqs: [
      { q: "Does it handle scanned PDFs?", a: "For best results use text-based PDFs. Scanned PDFs may need OCR first." },
      { q: "Are my financial data safe?", a: "Yes! All conversion happens locally in your browser." },
    ],
    keywords: ["pdf to excel", "pdf to xlsx", "extract pdf table", "convert pdf to excel free", "pdf to spreadsheet"],
  },
  {
    slug: "jpg-to-pdf-multiple-images",
    title: "JPG to PDF Converter - Convert Images to PDF Free",
    description: "Convert JPG, PNG images to PDF online. Combine multiple images into one PDF. Free, no sign up, browser-based.",
    h1: "Convert JPG to PDF Online Free",
    intro: "Turn your images into professional PDF documents. Convert single or multiple JPG, PNG images into one PDF file — perfect for scanned documents, photo albums, and portfolios.",
    steps: [
      { step: 1, title: "Upload Images", desc: "Select one or multiple JPG/PNG files." },
      { step: 2, title: "Arrange Order", desc: "Reorder images as you want them in the PDF." },
      { step: 3, title: "Convert & Download", desc: "Get your PDF instantly." },
    ],
    toolLink: "/jpg-to-pdf",
    toolName: "JPG to PDF Converter",
    faqs: [
      { q: "Can I combine multiple images into one PDF?", a: "Yes! Upload all your images and arrange them in order." },
      { q: "What formats are supported?", a: "JPG, JPEG, PNG, and most common image formats." },
      { q: "Is quality preserved?", a: "Yes, images are embedded at original quality." },
    ],
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf", "png to pdf", "photo to pdf", "images to pdf"],
  },
  {
    slug: "word-to-pdf-online-free",
    title: "Word to PDF Converter - Free Online Conversion",
    description: "Convert Word DOCX to PDF free online. Preserve formatting, fonts, and layout. No sign up, browser-based security.",
    h1: "Convert Word to PDF Online Free",
    intro: "Convert your Word documents to PDF format instantly. Our free Word to PDF converter preserves all formatting, fonts, and images — and everything happens in your browser.",
    steps: [
      { step: 1, title: "Upload Word File", desc: "Select your .docx file." },
      { step: 2, title: "Convert", desc: "Instantly converts to PDF." },
      { step: 3, title: "Download PDF", desc: "Your PDF is ready to share." },
    ],
    toolLink: "/word-to-pdf",
    toolName: "Word to PDF Converter",
    faqs: [
      { q: "Will formatting be preserved?", a: "Yes, fonts, images, tables and layout are preserved." },
      { q: "Is it free?", a: "Completely free, no limits." },
    ],
    keywords: ["word to pdf", "docx to pdf", "convert word to pdf", "word to pdf converter", "doc to pdf"],
  },
  {
    slug: "split-pdf-online-free",
    title: "Split PDF - Free Online PDF Splitter",
    description: "Split PDF pages into separate files free online. Extract specific pages, split by range. No sign up, browser-based.",
    h1: "Split PDF Files Online Free",
    intro: "Need to extract specific pages from a PDF or split a large document into smaller files? Our free PDF splitter makes it easy — choose pages, split, and download instantly.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF you want to split." },
      { step: 2, title: "Choose Split Method", desc: "Split all pages, by range, or select specific pages." },
      { step: 3, title: "Download Files", desc: "Get individual PDFs or a ZIP of all files." },
    ],
    toolLink: "/split-pdf",
    toolName: "PDF Splitter",
    faqs: [
      { q: "Can I extract specific pages?", a: "Yes, choose any pages or ranges to extract." },
      { q: "How many files can I create?", a: "As many as you need. No limits." },
    ],
    keywords: ["split pdf", "pdf splitter", "extract pdf pages", "split pdf online", "separate pdf pages"],
  },
  {
    slug: "unlock-pdf-online-free",
    title: "Unlock PDF - Remove PDF Password Free Online",
    description: "Remove password protection from PDF files free online. Unlock PDF restrictions instantly. No sign up, browser-based.",
    h1: "Unlock PDF Files Online Free",
    intro: "Got a PDF that's password protected or has restrictions? Our free PDF unlocker removes owner passwords and restrictions — all in your browser, with no upload to any server.",
    steps: [
      { step: 1, title: "Upload Protected PDF", desc: "Select your locked PDF file." },
      { step: 2, title: "Enter Password (Optional)", desc: "If you know the password, enter it. Otherwise we'll try to remove restrictions." },
      { step: 3, title: "Download Unlocked PDF", desc: "Get your restriction-free PDF." },
    ],
    toolLink: "/unlock-pdf",
    toolName: "PDF Unlocker",
    faqs: [
      { q: "Can you remove any PDF password?", a: "Owner/restriction passwords can be removed. User passwords (to open) need the correct password." },
      { q: "Is my document secure?", a: "All processing is local. Files never leave your browser." },
    ],
    keywords: ["unlock pdf", "remove pdf password", "pdf password remover", "unlock pdf free", "pdf unlocker"],
  },
  {
    slug: "protect-pdf-with-password",
    title: "Protect PDF - Add Password to PDF Free Online",
    description: "Add password protection to PDF files free online. Encrypt PDF with AES-256. No sign up, browser-based security.",
    h1: "Protect PDF with Password Online Free",
    intro: "Secure your sensitive PDF documents with password protection. Our free PDF protector uses AES-256 encryption — industry standard security — all done in your browser.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF to protect." },
      { step: 2, title: "Set Password", desc: "Create a strong password and set permissions." },
      { step: 3, title: "Download Protected PDF", desc: "Your encrypted PDF is ready." },
    ],
    toolLink: "/protect-pdf",
    toolName: "PDF Protector",
    faqs: [
      { q: "What encryption is used?", a: "AES-256 bit encryption — the same standard used by banks and governments." },
      { q: "Can I set printing restrictions?", a: "Yes, you can control printing, copying, and editing permissions." },
    ],
    keywords: ["protect pdf", "pdf password", "encrypt pdf", "pdf security", "lock pdf", "password protect pdf"],
  },
  {
    slug: "pdf-editor-online-free",
    title: "Edit PDF - Free Online PDF Editor, No Sign Up",
    description: "Edit PDF text and images online free. Modify PDF content directly in your browser. No registration, 100% secure.",
    h1: "Edit PDF Online Free - No Sign Up",
    intro: "Need to make changes to a PDF document? Our free online PDF editor lets you add text and modify content directly in your browser — no downloads, no registration.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF document to edit." },
      { step: 2, title: "Edit Content", desc: "Add text, modify existing content." },
      { step: 3, title: "Download Edited PDF", desc: "Save and download your modified PDF." },
    ],
    toolLink: "/edit-pdf",
    toolName: "PDF Editor",
    faqs: [
      { q: "What can I edit in a PDF?", a: "Add text overlays, annotations, and modify existing content." },
      { q: "Is this a full PDF editor?", a: "It covers common editing needs. For complex layouts, dedicated software may work better." },
    ],
    keywords: ["edit pdf", "pdf editor", "online pdf editor", "free pdf editor", "modify pdf", "edit pdf free"],
  },
  {
    slug: "sign-pdf-online-free",
    title: "Sign PDF - Free Online PDF Signature Tool, No Sign Up",
    description: "Add digital signature to PDF free online. Draw, type or upload your signature. Browser-based, 100% secure.",
    h1: "Sign PDF Documents Online Free",
    intro: "Add your signature to any PDF document in seconds. Draw your signature, type it, or upload an image — all free, all in your browser with no registration.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the document to sign." },
      { step: 2, title: "Create Signature", desc: "Draw, type or upload your signature." },
      { step: 3, title: "Place & Download", desc: "Position your signature and download the signed PDF." },
    ],
    toolLink: "/sign-pdf",
    toolName: "PDF Signer",
    faqs: [
      { q: "Is this legally binding?", a: "This provides a digital signature. For legally binding e-signatures, consult local regulations." },
      { q: "Can I save my signature?", a: "You can upload and reuse a saved signature image." },
    ],
    keywords: ["sign pdf", "pdf signature", "digital signature pdf", "esign pdf", "sign pdf free", "pdf sign online"],
  },
  {
    slug: "rotate-pdf-online-free",
    title: "Rotate PDF Pages - Free Online PDF Rotator",
    description: "Rotate PDF pages online free. Flip individual or all pages. No sign up, browser-based, instant rotation.",
    h1: "Rotate PDF Pages Online Free",
    intro: "Got a PDF with pages in the wrong orientation? Rotate individual pages or all pages at once — 90°, 180°, or 270° — totally free and in your browser.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF with rotated pages." },
      { step: 2, title: "Choose Pages & Rotation", desc: "Select pages and rotate direction." },
      { step: 3, title: "Download Rotated PDF", desc: "Get your correctly oriented PDF." },
    ],
    toolLink: "/rotate-pdf",
    toolName: "PDF Rotator",
    faqs: [
      { q: "Can I rotate individual pages?", a: "Yes, rotate any page independently." },
      { q: "Does rotation affect quality?", a: "No, rotation is lossless." },
    ],
    keywords: ["rotate pdf", "pdf rotator", "rotate pdf pages", "flip pdf", "rotate pdf online"],
  },
  {
    slug: "ocr-pdf-to-text",
    title: "OCR PDF - Extract Text from Scanned PDF Free",
    description: "Extract text from scanned PDFs with OCR free online. Convert image PDFs to searchable text. No sign up, browser-based.",
    h1: "OCR PDF - Extract Text from Scanned PDF Free",
    intro: "Have a scanned document or image-based PDF you need to extract text from? Our free OCR (Optical Character Recognition) tool converts your scanned PDFs into readable, searchable text — right in your browser.",
    steps: [
      { step: 1, title: "Upload Scanned PDF", desc: "Select your image-based or scanned PDF." },
      { step: 2, title: "OCR Processing", desc: "Our OCR engine extracts text from images." },
      { step: 3, title: "Get Editable Text", desc: "Copy or download the extracted text." },
    ],
    toolLink: "/ocr-pdf",
    toolName: "PDF OCR",
    faqs: [
      { q: "How accurate is the OCR?", a: "Accuracy depends on scan quality. Clear, high-resolution scans work best." },
      { q: "What languages are supported?", a: "Multiple languages including Turkish and English." },
    ],
    keywords: ["ocr pdf", "pdf ocr", "scanned pdf to text", "extract text from pdf", "pdf text recognition", "ocr free"],
  },
  {
    slug: "high-quality-pdf-to-jpg",
    title: "PDF to JPG - High Quality Image Conversion Free",
    description: "Convert PDF pages to high quality JPG images free online. Extract single or all pages as images. No sign up, browser-based.",
    h1: "Convert PDF to JPG Images Online Free",
    intro: "Need to extract pages from a PDF as images? Our free PDF to JPG converter creates high-resolution images from your PDF pages — perfect for presentations, social media, and archiving.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF file." },
      { step: 2, title: "Choose Pages", desc: "Convert all pages or specific ones." },
      { step: 3, title: "Download JPGs", desc: "Get high-quality JPG images of each page." },
    ],
    toolLink: "/pdf-to-jpg",
    toolName: "PDF to JPG Converter",
    faqs: [
      { q: "What resolution are the images?", a: "High resolution, suitable for printing and web use." },
      { q: "Can I convert all pages at once?", a: "Yes, every page becomes a separate JPG file." },
    ],
    keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpg", "pdf to png", "pdf page to image", "high quality pdf to jpg"],
  },
  {
    slug: "repair-corrupted-pdf",
    title: "Repair PDF - Fix Corrupted PDF Files Free Online",
    description: "Repair damaged and corrupted PDF files free online. Fix PDFs that won't open. No sign up, browser-based recovery.",
    h1: "Repair Corrupted PDF Files Online Free",
    intro: "Can't open a PDF file? It might be corrupted. Our free PDF repair tool can fix many common PDF corruption issues and recover your document — all in your browser.",
    steps: [
      { step: 1, title: "Upload Damaged PDF", desc: "Select the PDF that won't open." },
      { step: 2, title: "Auto-Detect & Repair", desc: "Our engine detects and fixes common issues." },
      { step: 3, title: "Download Repaired PDF", desc: "Get your recovered PDF file." },
    ],
    toolLink: "/repair-pdf",
    toolName: "PDF Repair Tool",
    faqs: [
      { q: "What kinds of corruption can be fixed?", a: "Structural corruption, header issues, and common file errors." },
      { q: "Is recovery guaranteed?", a: "Not always, but our tool has a high success rate with common corruption." },
    ],
    keywords: ["repair pdf", "fix corrupted pdf", "recover pdf", "broken pdf fix", "pdf repair tool", "pdf error fix"],
  },
  {
    slug: "convert-pdf-to-word-keep-formatting",
    title: "Convert PDF to Word - Keep Formatting Free Online",
    description: "Convert PDF to Word keeping original formatting. Free, no sign up, 100% browser-based. Preserve fonts, tables, images and layout.",
    h1: "Convert PDF to Word Without Losing Formatting",
    intro: "Tired of PDF to Word converters that mess up your formatting? Our converter preserves fonts, tables, images, and layout — everything stays exactly where it should be.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF file. Works with any size." },
      { step: 2, title: "Convert", desc: "Our engine extracts text and preserves formatting." },
      { step: 3, title: "Download DOCX", desc: "Get your perfectly formatted Word document." },
    ],
    toolLink: "/pdf-to-word", toolName: "PDF to Word Converter",
    faqs: [{ q: "Will tables stay intact?", a: "Yes, our converter preserves table structure, borders, and content." }, { q: "Do fonts stay the same?", a: "Fonts are preserved when available, with close fallbacks when not." }],
    keywords: ["pdf to word keep formatting", "convert pdf to word", "pdf to docx", "pdf word converter"],
  },
  {
    slug: "compress-pdf-reduce-file-size",
    title: "Compress PDF - Reduce File Size Without Losing Quality",
    description: "Compress PDF files and reduce size by up to 90% free. No sign up, browser-based. Perfect for email attachments and web uploads.",
    h1: "Compress PDF to Reduce File Size Online Free",
    intro: "Is your PDF too large to email or upload? Compress it instantly while keeping document quality. Reduce your PDF file size by up to 90% — all free, all in your browser.",
    steps: [
      { step: 1, title: "Upload", desc: "Select your large PDF file." },
      { step: 2, title: "Choose Level", desc: "Low, recommended, or extreme compression." },
      { step: 3, title: "Download", desc: "Get your optimized, smaller PDF." },
    ],
    toolLink: "/compress-pdf", toolName: "PDF Compressor",
    faqs: [{ q: "How small can I make my PDF?", a: "Up to 90% reduction. Image-heavy PDFs compress the most." }, { q: "Will quality suffer?", a: "Recommended mode maintains quality. Extreme mode prioritizes size." }],
    keywords: ["compress pdf", "reduce pdf size", "pdf compressor", "make pdf smaller", "pdf size reducer"],
  },
  {
    slug: "pdf-to-excel-converter-online",
    title: "PDF to Excel Converter - Extract Tables Free Online",
    description: "Convert PDF tables to Excel XLSX free online. Extract financial data, reports, and tables. No sign up, 100% browser-based.",
    h1: "Extract Tables from PDF to Excel Online Free",
    intro: "Got a PDF full of financial data or tables? Our PDF to Excel converter extracts tables and data into clean Excel spreadsheets — ready for analysis.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF with tables." },
      { step: 2, title: "Extract", desc: "Tables are automatically detected and converted." },
      { step: 3, title: "Download XLSX", desc: "Open in Excel, Google Sheets, or any spreadsheet app." },
    ],
    toolLink: "/pdf-to-excel", toolName: "PDF to Excel Converter",
    faqs: [{ q: "What if my PDF has multiple tables?", a: "Each table is extracted into separate sheets or cells." }, { q: "Can it handle scanned PDFs?", a: "Text-based PDFs work best. For scanned documents, try OCR first." }],
    keywords: ["pdf to excel", "extract pdf table", "pdf to xlsx", "convert pdf to excel", "pdf excel converter"],
  },
  {
    slug: "split-pdf-extract-pages",
    title: "Split PDF - Extract Specific Pages Free Online",
    description: "Extract specific pages from PDF free online. Split PDF by page range, extract individual pages. No sign up, browser-based.",
    h1: "Extract Pages from PDF Online Free",
    intro: "Need just a few pages from a long PDF? Extract specific pages or split your document into smaller files — it's easy, free, and secure.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF to extract from." },
      { step: 2, title: "Choose Pages", desc: "Select specific pages or page ranges." },
      { step: 3, title: "Download", desc: "Get your extracted pages as a new PDF." },
    ],
    toolLink: "/split-pdf", toolName: "PDF Splitter",
    faqs: [{ q: "Can I extract non-consecutive pages?", a: "Yes! Select any combination of pages or ranges." }, { q: "Does it work for large PDFs?", a: "Yes, files of any size are supported." }],
    keywords: ["split pdf", "extract pdf pages", "pdf splitter", "pdf page extractor", "separate pdf"],
  },
  {
    slug: "pdf-editor-add-text",
    title: "PDF Editor - Add Text to PDF Free Online",
    description: "Add text to PDF documents free online. Edit PDF content without Adobe Acrobat. No sign up, browser-based editor.",
    h1: "Add Text to PDF Documents Online Free",
    intro: "Need to add text or fill out a PDF form? Our free online PDF editor lets you add text overlays directly to any PDF — no software needed.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF to edit." },
      { step: 2, title: "Add Text", desc: "Click anywhere to add text boxes." },
      { step: 3, title: "Download", desc: "Save your edited PDF." },
    ],
    toolLink: "/edit-pdf", toolName: "PDF Editor",
    faqs: [{ q: "Can I change existing text?", a: "Our editor adds text overlays. For full editing, convert to Word first." }, { q: "Is the editing permanent?", a: "Yes, the text you add is embedded in the PDF." }],
    keywords: ["edit pdf", "add text to pdf", "pdf editor", "write on pdf", "pdf text editor"],
  },
  {
    slug: "pdf-page-deleter",
    title: "Delete Pages from PDF - Free Online PDF Page Remover",
    description: "Delete unwanted pages from PDF files free online. Remove blank pages, extra pages. No sign up, browser-based.",
    h1: "Delete Pages from PDF Online Free",
    intro: "Got a PDF with blank pages or pages you don't need? Remove unwanted pages in seconds — just select and delete.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF file." },
      { step: 2, title: "Select Pages", desc: "Click pages you want to remove." },
      { step: 3, title: "Download", desc: "Get your cleaned PDF." },
    ],
    toolLink: "/delete-pages", toolName: "PDF Page Deleter",
    faqs: [{ q: "Can I delete multiple pages at once?", a: "Yes, select as many pages as you want to remove." }, { q: "What if I delete the wrong page?", a: "Use the undo button before downloading." }],
    keywords: ["delete pdf pages", "remove pdf pages", "pdf page remover", "pdf page deleter", "delete pages from pdf"],
  },
  {
    slug: "pdf-watermark-adder",
    title: "Add Watermark to PDF - Free Online PDF Watermark Tool",
    description: "Add text watermark to PDF files free online. Brand your documents, add confidential stamps. No sign up, browser-based.",
    h1: "Add Watermark to PDF Documents Online Free",
    intro: "Brand your documents or add confidential/draft stamps to your PDFs. Add professional text watermarks with full control over opacity and position.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF to watermark." },
      { step: 2, title: "Create Watermark", desc: "Enter text, set opacity and font size." },
      { step: 3, title: "Download", desc: "Get your watermarked PDF." },
    ],
    toolLink: "/watermark-pdf", toolName: "PDF Watermark Tool",
    faqs: [{ q: "Can I customize the watermark?", a: "Yes! Control text, opacity, font size, and position." }, { q: "Will watermark appear on all pages?", a: "Yes, watermarks are applied to every page." }],
    keywords: ["watermark pdf", "add watermark to pdf", "pdf watermark", "confidential stamp pdf", "draft watermark pdf"],
  },
  {
    slug: "pdf-metadata-editor",
    title: "Edit PDF Metadata - Change Title, Author, Keywords Free",
    description: "Edit PDF metadata online free. Change title, author, subject, keywords. No sign up, browser-based metadata editor.",
    h1: "Edit PDF Metadata Online Free",
    intro: "Need to update the title, author, or keywords of a PDF? Our free metadata editor lets you modify document properties in seconds.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF to edit." },
      { step: 2, title: "Edit Fields", desc: "Change title, author, subject, keywords." },
      { step: 3, title: "Download", desc: "Get your updated PDF with new metadata." },
    ],
    toolLink: "/edit-metadata", toolName: "PDF Metadata Editor",
    faqs: [{ q: "What metadata can I edit?", a: "Title, author, subject, keywords, and creator fields." }, { q: "Why edit PDF metadata?", a: "Better searchability, proper attribution, and SEO optimization." }],
    keywords: ["edit pdf metadata", "pdf metadata editor", "change pdf title", "pdf author", "pdf keywords"],
  },
  {
    slug: "free-pdf-converter-no-email",
    title: "Free PDF Converter - No Email Required, Convert Online",
    description: "Convert PDF files free online without email or sign up. PDF to Word, Excel, JPG and more. 100% browser-based, secure.",
    h1: "Free PDF Converter - No Email, No Sign Up",
    intro: "Tired of websites asking for your email just to convert a PDF? Our free PDF converter works instantly with no registration, no email, no hassle.",
    steps: [
      { step: 1, title: "Upload", desc: "Select any PDF file." },
      { step: 2, title: "Choose Format", desc: "Convert to Word, Excel, JPG, or any format." },
      { step: 3, title: "Download", desc: "Get your converted file instantly." },
    ],
    toolLink: "/pdf-to-word", toolName: "PDF Converter",
    faqs: [{ q: "Do I need to provide email?", a: "No! Convert unlimited PDFs without any registration." }, { q: "What formats can I convert to?", a: "Word, Excel, PowerPoint, JPG, PNG, HTML, and many more." }],
    keywords: ["free pdf converter", "pdf converter no email", "free pdf conversion", "convert pdf online free"],
  },
  {
    slug: "pdf-editor-free-no-watermark",
    title: "PDF Editor - Free, No Watermark Online Tool",
    description: "Edit PDF documents free online without watermarks. Add text, annotate, and modify PDFs. No sign up, 100% browser-based.",
    h1: "Edit PDF Online Free - No Watermark",
    intro: "Many free PDF editors add watermarks to your documents. Not ours. Edit your PDFs freely with no watermarks, no registration, and no hidden fees.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF to edit." },
      { step: 2, title: "Edit", desc: "Add text, annotations, and make changes." },
      { step: 3, title: "Download", desc: "Get your clean, watermark-free PDF." },
    ],
    toolLink: "/edit-pdf", toolName: "PDF Editor",
    faqs: [{ q: "Will there be a watermark?", a: "Never. Your PDFs stay clean and professional." }, { q: "Is it really free?", a: "Yes, completely free with no watermarks or limits." }],
    keywords: ["pdf editor no watermark", "free pdf editor", "edit pdf free", "pdf editor online free"],
  },
  {
    slug: "how-to-remove-pages-from-pdf",
    title: "Remove Pages from PDF - Free Online Tool",
    description: "Learn how to delete pages from PDF files. Remove extra, blank, or unwanted pages from PDF free online. Step by step guide.",
    h1: "How to Remove Pages from PDF Files Online Free",
    intro: "Need to remove blank pages or unwanted content from your PDF? Our free tool lets you delete pages in seconds — just select and remove.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF file." },
      { step: 2, title: "Select Pages", desc: "Click on pages you want to delete." },
      { step: 3, title: "Download", desc: "Get your PDF without the removed pages." },
    ],
    toolLink: "/delete-pages", toolName: "PDF Page Remover",
    faqs: [{ q: "Can I undo deleted pages?", a: "Yes! Use the undo button before downloading." }, { q: "How many pages can I delete?", a: "As many as you want. No limits." }],
    keywords: ["remove pages from pdf", "delete pdf pages", "how to remove pdf pages", "pdf page remover"],
  },
  {
    slug: "crop-pdf-pages-free",
    title: "Crop PDF Pages - Free Online PDF Cropper",
    description: "Crop and trim PDF pages online free. Remove unwanted margins, white space. No sign up, browser-based cropping tool.",
    h1: "Crop PDF Pages Online Free",
    intro: "Got a PDF with too much white space or unwanted margins? Crop it perfectly with our free online PDF cropper. Select the area you want to keep and crop the rest.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF." },
      { step: 2, title: "Select Area", desc: "Drag to select the area you want to keep." },
      { step: 3, title: "Crop & Download", desc: "Get your perfectly cropped PDF." },
    ],
    toolLink: "/crop-pdf", toolName: "PDF Cropper",
    faqs: [{ q: "Can I crop specific pages?", a: "Yes, crop individual pages or apply to all." }, { q: "Will cropping affect quality?", a: "No, cropping is lossless." }],
    keywords: ["crop pdf", "pdf cropper", "crop pdf pages", "trim pdf margins", "pdf crop tool"],
  },
  {
    slug: "pdf-to-grayscale-converter",
    title: "PDF to Grayscale Converter - Free Online Tool",
    description: "Convert colored PDF to grayscale/black and white free online. Save ink, reduce file size. No sign up, browser-based.",
    h1: "Convert PDF to Grayscale Online Free",
    intro: "Converting your PDF to grayscale saves ink, reduces file size, and looks professional. Our free tool converts your entire PDF to grayscale in seconds.",
    steps: [
      { step: 1, title: "Upload", desc: "Select your colored PDF." },
      { step: 2, title: "Convert", desc: "Automatically converted to grayscale." },
      { step: 3, title: "Download", desc: "Get your black and white PDF." },
    ],
    toolLink: "/grayscale-pdf", toolName: "PDF Grayscale Converter",
    faqs: [{ q: "Will it reduce file size?", a: "Yes, grayscale PDFs are typically 30-50% smaller." }, { q: "Is text still searchable?", a: "Yes, text remains searchable and selectable." }],
    keywords: ["pdf to grayscale", "grayscale pdf converter", "convert pdf to black and white", "pdf bw converter"],
  },
  {
    slug: "extract-images-from-pdf",
    title: "Extract Images from PDF - Free Online Tool",
    description: "Extract embedded images from PDF files free online. Save all images from PDF pages. No sign up, browser-based extraction.",
    h1: "Extract Images from PDF Files Online Free",
    intro: "Need to extract all the images from a PDF document? Our tool pulls out embedded images from every page — perfect for reusing graphics, photos, and illustrations.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the PDF with images." },
      { step: 2, title: "Extract", desc: "All images are automatically extracted." },
      { step: 3, title: "Download", desc: "Get your images as PNG files." },
    ],
    toolLink: "/pdf-to-png", toolName: "Image Extractor",
    faqs: [{ q: "What image formats are extracted?", a: "PNG format for best quality. All embedded images are extracted." }, { q: "Are images in original quality?", a: "Yes, images are extracted at their original resolution." }],
    keywords: ["extract images from pdf", "pdf image extractor", "save images from pdf", "pdf to image", "extract pdf images"],
  },
  {
    slug: "pdf-header-footer-adder",
    title: "Add Header and Footer to PDF - Free Online Tool",
    description: "Add headers and footers to PDF documents free online. Add page numbers, titles, dates. No sign up, browser-based.",
    h1: "Add Header and Footer to PDF Online Free",
    intro: "Want to add page numbers, document titles, or dates to your PDF? Our free tool lets you add professional headers and footers to every page.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your document." },
      { step: 2, title: "Add Text", desc: "Configure header and footer text." },
      { step: 3, title: "Download", desc: "Get your PDF with headers and footers." },
    ],
    toolLink: "/edit-pdf", toolName: "PDF Header/Footer Tool",
    faqs: [{ q: "Can I add page numbers?", a: "Yes! Add page numbers, dates, titles, and any custom text." }, { q: "Will it appear on every page?", a: "Yes, headers and footers appear on all pages." }],
    keywords: ["add header footer pdf", "pdf header footer", "add page numbers pdf", "pdf header tool"],
  },
  {
    slug: "pdf-page-size-changer",
    title: "Change PDF Page Size - Free Online Resizer",
    description: "Change PDF page size online free. Convert A4 to Letter, A3 to A4 and more. No sign up, browser-based page resizer.",
    h1: "Change PDF Page Size Online Free",
    intro: "Need to resize your PDF pages? Convert between A4, Letter, A3, Legal and any custom size. Perfect for preparing documents for print or digital distribution.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF file." },
      { step: 2, title: "Choose Size", desc: "Select A4, Letter, or custom size." },
      { step: 3, title: "Download", desc: "Get your resized PDF." },
    ],
    toolLink: "/edit-pdf", toolName: "PDF Page Resizer",
    faqs: [{ q: "What sizes are supported?", a: "A4, A3, Letter, Legal, and custom dimensions." }, { q: "Will content scale?", a: "Yes, content is scaled to fit the new page size." }],
    keywords: ["change pdf page size", "pdf page resizer", "a4 to letter pdf", "resize pdf pages", "pdf page size converter"],
  },
  {
    slug: "pdf-to-png-high-quality",
    title: "PDF to PNG Converter - High Quality, Free Online",
    description: "Convert PDF pages to high quality PNG images free online. Lossless conversion. No sign up, browser-based.",
    h1: "Convert PDF to PNG Images Online Free",
    intro: "Convert your PDF pages to crystal-clear PNG images. Unlike JPG, PNG preserves text sharpness with lossless compression — perfect for documents and presentations.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select your PDF file." },
      { step: 2, title: "Convert", desc: "All pages converted to PNG." },
      { step: 3, title: "Download", desc: "Get individual PNGs or ZIP of all pages." },
    ],
    toolLink: "/pdf-to-png", toolName: "PDF to PNG Converter",
    faqs: [{ q: "Why PNG instead of JPG?", a: "PNG is lossless — text stays sharp. JPG can blur text and create artifacts." }, { q: "Can I download all pages at once?", a: "Yes, download a ZIP with all pages or individual files." }],
    keywords: ["pdf to png", "pdf to png converter", "high quality pdf to png", "convert pdf to png", "pdf png converter"],
  },
  {
    slug: "add-signature-to-pdf-free",
    title: "Add Signature to PDF - Free Online Signing Tool",
    description: "Add your signature to PDF documents free online. Draw, type or upload signature. No sign up, 100% browser-based.",
    h1: "Add Signature to PDF Documents Online Free",
    intro: "Sign your PDF documents electronically in seconds. Draw your signature with your mouse, type it in cursive, or upload a scanned image — all free, all secure.",
    steps: [
      { step: 1, title: "Upload PDF", desc: "Select the document to sign." },
      { step: 2, title: "Create Signature", desc: "Draw, type, or upload your signature." },
      { step: 3, title: "Download", desc: "Get your signed PDF instantly." },
    ],
    toolLink: "/sign-pdf", toolName: "PDF Signing Tool",
    faqs: [{ q: "Can I save my signature for reuse?", a: "Yes, upload your signature image and reuse it." }, { q: "Is it legally binding?", a: "This provides a digital signature. For legally binding e-signatures, consult local laws." }],
    keywords: ["add signature to pdf", "sign pdf free", "pdf signature tool", "electronic signature pdf", "pdf sign online"],
  },
];

export function getLandingPage(slug: string): LandingPage | undefined {
  return landingPages.find(p => p.slug === slug);
}

export function getAllLandingSlugs(): string[] {
  return landingPages.map(p => p.slug);
}